# Generated by Django 4.2.7 on 2023-11-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_page_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
